# 1. GENERAR DATASET

In [81]:
import pandas as pd
import glob
import os

ruta = "PV_MaximumPowerPredictor/*.csv"

dfs = []

for archivo in glob.glob(ruta):
    
    nombre = os.path.basename(archivo).replace(".csv","")
    
    partes = nombre.split("_")
    
    parque_id = partes[0]              # Cocoa / Golden / Eugene
    panel_id = "_".join(partes[1:])    # tipo de panel
    
    df = pd.read_csv(archivo)
    
    # eliminar timestamp
    df = df.drop(columns=["Time Stamp (local standard time) yyyy-mm-ddThh:mm:ss"], errors="ignore")
    
    # añadir columnas
    df["parque_id"] = parque_id
    df["panel_id"] = panel_id
    
    # mover columnas al inicio
    cols = ["parque_id","panel_id"] + [c for c in df.columns if c not in ["parque_id","panel_id"]]
    df = df[cols]
    
    dfs.append(df)

dataset_total = pd.concat(dfs, ignore_index=True)

print(dataset_total.shape)
dataset_total.head()

(1025599, 12)

,parque_id,panel_id,POA irradiance CMP22 pyranometer (W/m2),PV module back surface temperature (degC),Pmp (W),Dry bulb temperature (degC),Relative humidity (%RH),Atmospheric pressure (mb),Precipitation (mm) accumulated daily total,Direct normal irradiance (W/m2),Global horizontal irradiance (W/m2),Diffuse horizontal irradiance (W/m2)
0,Cocoa,aSiMicro03036_cleaned,20.2,19.3,1.9610,17.7,96.0,1009.8,20.3,0.1,21.9,22.2
1,Cocoa,aSiMicro03036_cleaned,35.8,19.5,3.7242,17.8,96.0,1009.7,20.3,0.1,38.4,39.0
2,Cocoa,aSiMicro03036_cleaned,20.2,19.5,1.9551,17.8,96.0,1009.9,20.3,0.1,20.1,20.3
3,Cocoa,aSiMicro03036_cleaned,20.6,19.5,2.0057,17.8,96.1,1009.8,20.3,0.1,21.4,21.8
4,Cocoa,aSiMicro03036_cleaned,29.5,19.5,3.1397,17.8,96.0,1009.9,20.6,0.1,29.3,29.5

# 2. EXPLORAR LOS DATOS

In [82]:
dataset_total["parque_id"].value_counts() # Comprobar num de parques y paneles

parque_id
Eugene    473348
Cocoa     421664
Golden    130587
Name: count, dtype: int64

In [83]:
dataset_total["panel_id"].nunique()

22

In [84]:
sorted(dataset_total["panel_id"].unique())

['CIGS1-001_cleaned',
 'CIGS39013_cleaned',
 'CIGS39017_cleaned',
 'CIGS8-001_cleaned',
 'CdTe75638_cleaned',
 'CdTe75669_cleaned',
 'HIT05662_cleaned',
 'HIT05667_cleaned',
 'aSiMicro03036_cleaned',
 'aSiMicro03038_cleaned',
 'aSiTandem72-46_cleaned',
 'aSiTandem90-31_cleaned',
 'aSiTriple28324_cleaned',
 'aSiTriple28325_cleaned',
 'mSi0166_cleaned',
 'mSi0188_cleaned',
 'mSi0247_cleaned',
 'mSi0251_cleaned',
 'mSi460A8_cleaned',
 'mSi460BB_cleaned',
 'xSi11246_cleaned',
 'xSi12922_cleaned']

In [85]:
pd.crosstab(dataset_total["parque_id"], dataset_total["panel_id"])

panel_id,CIGS1-001_cleaned,CIGS39013_cleaned,CIGS39017_cleaned,CIGS8-001_cleaned,CdTe75638_cleaned,CdTe75669_cleaned,HIT05662_cleaned,HIT05667_cleaned,aSiMicro03036_cleaned,aSiMicro03038_cleaned,...,aSiTriple28324_cleaned,aSiTriple28325_cleaned,mSi0166_cleaned,mSi0188_cleaned,mSi0247_cleaned,mSi0251_cleaned,mSi460A8_cleaned,mSi460BB_cleaned,xSi11246_cleaned,xSi12922_cleaned
parque_id,,,,,,,,,,,,,,,,,,,,,
Cocoa,0,0,34775,38939,39080,0,0,38377,39037,0,...,38485,0,36765,39102,0,0,38929,0,0,38989
Eugene,0,0,42674,43146,42248,0,0,43271,43343,0,...,42705,0,43268,43127,0,0,43115,0,0,43185
Golden,12011,11437,0,0,0,11953,11876,0,0,12148,...,0,11445,0,0,11912,11887,0,11919,11929,0

In [86]:
dataset_total.isna().sum()

parque_id                                     0
panel_id                                      0
POA irradiance CMP22 pyranometer (W/m2)       0
PV module back surface temperature (degC)     0
Pmp (W)                                       0
Dry bulb temperature (degC)                   0
Relative humidity (%RH)                       0
Atmospheric pressure (mb)                     0
Precipitation (mm) accumulated daily total    0
Direct normal irradiance (W/m2)               0
Global horizontal irradiance (W/m2)           0
Diffuse horizontal irradiance (W/m2)          0
dtype: int64

# 3. MODELO BASELINE

No ignoramos el parque y el panel, solo el timestamp.

In [87]:
from sklearn.preprocessing import LabelEncoder

le_parque = LabelEncoder()
le_panel  = LabelEncoder()

dataset_total["parque_enc"] = le_parque.fit_transform(dataset_total["parque_id"])
dataset_total["panel_enc"]  = le_panel.fit_transform(dataset_total["panel_id"])

In [88]:
df_model = dataset_total.drop(columns=["parque_id", "panel_id"])

In [89]:
X = df_model.drop(columns=["Pmp (W)"])
y = df_model["Pmp (W)"]

In [90]:
from sklearn.model_selection import train_test_split

# Primero separar test (20%)
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Luego separar val del resto (20% del total = 25% de train_val)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42
)

# Resultado: 60% train, 20% val, 20% test
print(X_train.shape, X_val.shape, X_test.shape)

(615359, 11) (205120, 11) (205120, 11)

In [91]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.fit_transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [92]:
import numpy as np

np.mean(X_train_scaled, axis=0)

array([-5.35540588e-17, -7.48036350e-16,  9.28362727e-18,  6.21795185e-17,
       -4.20880863e-18, -2.36132062e-17,  2.52153247e-17,  1.32037659e-17,
        4.07428841e-17,  8.67337889e-17,  3.26428039e-17])

In [93]:
np.std(X_train_scaled, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [94]:
import torch

X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_val_tensor = torch.tensor(X_val_scaled, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1,1)
y_val_tensor = torch.tensor(y_val.values, dtype=torch.float32).view(-1,1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1,1)

## A. DISEÑO DEL MODELO

In [95]:
import torch
import torch.nn as nn

class PVModel(nn.Module):
    
    def __init__(self):
        super().__init__()
        
        self.model = nn.Sequential(
            nn.Linear(11, 64),
            nn.ReLU(),
            
            nn.Linear(64, 32),
            nn.ReLU(),
            
            nn.Linear(32, 16),
            nn.ReLU(),
            
            nn.Linear(16, 1)
        )
        
    def forward(self, x):
        return self.model(x)

In [96]:
class PVModelV2(nn.Module):
    
    def __init__(self, input_size=11):
        super().__init__()
        
        self.model = nn.Sequential(
            nn.Linear(input_size, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(64, 32),
            nn.BatchNorm1d(32),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(32, 16),
            nn.BatchNorm1d(16),
            nn.ReLU(),
            nn.Dropout(0.2),
            
            nn.Linear(16, 1)
        )
        
    def forward(self, x):
        return self.model(x)

In [97]:
model = PVModel()
print(model)

model2 = PVModelV2()
print(model2)

PVModel(
  (model): Sequential(
    (0): Linear(in_features=11, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=16, bias=True)
    (5): ReLU()
    (6): Linear(in_features=16, out_features=1, bias=True)
  )
)
PVModelV2(
  (model): Sequential(
    (0): Linear(in_features=11, out_features=64, bias=True)
    (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=64, out_features=32, bias=True)
    (5): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=32, out_features=16, bias=True)
    (9): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU()
    (11): Dropout(p=0.2, inplace=False)
    (12): Linear(in_features=16, out_features=1, bias=True)
  )
)

In [98]:
model(X_train_tensor[:5])

tensor([[0.3080],
        [0.3077],
        [0.3236],
        [0.2994],
        [0.3146]], grad_fn=<AddmmBackward0>)

In [99]:
model2(X_train_tensor[:5])

tensor([[ 0.1858],
        [ 0.4782],
        [-0.0651],
        [ 0.8272],
        [-0.1635]], grad_fn=<AddmmBackward0>)

In [100]:
criterion = nn.MSELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [101]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(
    train_dataset,
    batch_size=1024,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=1024
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1024
)

## B. ML FLOW

In [102]:
import mlflow

In [103]:
mlflow.set_tracking_uri("file:./mlruns")
mlflow.set_experiment("PV_Power")

<Experiment: artifact_location='file:///c:/Users/User/Documents/GitHub/Reto3_MicroRedes/OBJETIVO2/mlruns/427506226560148484', creation_time=1773741607353, experiment_id='427506226560148484', last_update_time=1773741607353, lifecycle_stage='active', name='PV_Power', tags={}, workspace='default'>

In [104]:
class PVModel(nn.Module):
    
    def __init__(self, layers_sizes, input_size=11):
        super().__init__()
        
        layers = []
        
        for size in layers_sizes:
            layers.append(nn.Linear(input_size, size))
            layers.append(nn.ReLU())
            input_size = size
        
        layers.append(nn.Linear(input_size, 1))
        
        self.model = nn.Sequential(*layers)
        
    def forward(self, x):
        return self.model(x)

In [105]:
class PVModelV2(nn.Module):
    
    def __init__(self, layers_sizes,dropout, input_size=11):
        super().__init__()
        
        layers = []
        
        for size in layers_sizes:
            layers.append(nn.Linear(input_size, size))
            layers.append(nn.BatchNorm1d(size))   # nuevo
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))         # nuevo
            input_size = size
        
        layers.append(nn.Linear(input_size, 1))
        
        self.model = nn.Sequential(*layers)
        
    def forward(self, x):
        return self.model(x)

In [106]:
def evaluate(model, loader, criterion):
    
    model.eval()
    total_loss = 0
    
    with torch.no_grad():
        for X_batch, y_batch in loader:
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            total_loss += loss.item()
    
    return total_loss / len(loader)

In [107]:
def train_model(arch, lr, epochs, model,dropout=0):
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    best_val_loss = float("inf")
    patience = 5
    counter = 0
    
    with mlflow.start_run():
    
        mlflow.log_param("arquitectura", str(arch))
        mlflow.log_param("lr", lr)
        mlflow.log_param("dropout",dropout)
        for epoch in range(epochs):
            
            model.train()
            total_loss = 0
            
            for X_batch, y_batch in train_loader:
                
                y_pred = model(X_batch)
                loss = criterion(y_pred, y_batch)
                
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                
                total_loss += loss.item()
            
            train_loss = total_loss / len(train_loader)
            val_loss = evaluate(model, val_loader, criterion)
            
            mlflow.log_metric("train_loss", train_loss, step=epoch)
            mlflow.log_metric("val_loss", val_loss, step=epoch)
            
            print(f"Epoch {epoch+1} | Train: {train_loss:.2f} | Val: {val_loss:.2f}")

            # Early stopping
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                torch.save(model.state_dict(), f"best_model.pt")
                counter = 0
            else:
                counter += 1
            if counter >= patience:
                print(f"Early stopping en epoch {epoch+1}")
                break

    return model

In [108]:
arquitecturas = [
    [64, 32, 16],
    [128, 64, 32],
    [256, 128, 64]
]

learning_rates = [0.001, 0.0005]

dropouts = [0.1, 0.2]

epochs = 100

In [110]:
for arch in arquitecturas:
    for lr in learning_rates:
        model = PVModel(arch)
        print(f"\nEntrenando modelo {arch} con lr={lr}")
        
        train_model(arch, lr, epochs,model)

Entrenando modelo [64, 32, 16] con lr=0.001
Epoch 1 | Train: 821.36 | Val: 480.43
Epoch 2 | Train: 329.67 | Val: 243.12
Epoch 3 | Train: 195.12 | Val: 145.56
Epoch 4 | Train: 110.22 | Val: 86.81
Epoch 5 | Train: 73.26 | Val: 65.06
Epoch 6 | Train: 58.54 | Val: 53.41
Epoch 7 | Train: 51.18 | Val: 48.83
Epoch 8 | Train: 46.79 | Val: 48.12
Epoch 9 | Train: 43.82 | Val: 43.69
Epoch 10 | Train: 42.20 | Val: 41.61
Epoch 11 | Train: 40.14 | Val: 38.70
Epoch 12 | Train: 38.55 | Val: 37.07
Epoch 13 | Train: 36.96 | Val: 37.19
Epoch 14 | Train: 35.62 | Val: 35.71
Epoch 15 | Train: 34.36 | Val: 37.25
Epoch 16 | Train: 32.92 | Val: 32.96
Epoch 17 | Train: 31.93 | Val: 31.61
Epoch 18 | Train: 30.92 | Val: 32.61
Epoch 19 | Train: 30.23 | Val: 29.70
Epoch 20 | Train: 29.47 | Val: 28.49
Epoch 21 | Train: 28.46 | Val: 28.22
Epoch 22 | Train: 27.71 | Val: 27.16
Epoch 23 | Train: 27.17 | Val: 25.96
Epoch 24 | Train: 26.25 | Val: 27.46
Epoch 25 | Train: 25.74 | Val: 25.34
Epoch 26 | Train: 25.11 | Val: 24.48
Epoch 27 | Train: 24.82 | Val: 24.35
Epoch 28 | Train: 24.47 | Val: 25.14
Epoch 29 | Train: 23.85 | Val: 25.35
Epoch 30 | Train: 23.70 | Val: 23.36
Epoch 31 | Train: 23.18 | Val: 22.52
Epoch 32 | Train: 22.74 | Val: 24.35
Epoch 33 | Train: 22.62 | Val: 21.77
Epoch 34 | Train: 22.51 | Val: 21.18
Epoch 35 | Train: 22.11 | Val: 21.69
Epoch 36 | Train: 21.93 | Val: 22.98
Epoch 37 | Train: 21.21 | Val: 21.78
Epoch 38 | Train: 21.17 | Val: 20.40
Epoch 39 | Train: 20.80 | Val: 22.65
Epoch 40 | Train: 20.91 | Val: 22.07
Epoch 41 | Train: 20.33 | Val: 20.24
Epoch 42 | Train: 20.29 | Val: 20.78
Epoch 43 | Train: 20.17 | Val: 20.62
Epoch 44 | Train: 19.65 | Val: 20.48
Epoch 45 | Train: 19.42 | Val: 23.07
Epoch 46 | Train: 19.31 | Val: 18.67
Epoch 47 | Train: 19.10 | Val: 18.86
Epoch 48 | Train: 18.87 | Val: 18.63
Epoch 49 | Train: 18.83 | Val: 18.78
Epoch 50 | Train: 18.36 | Val: 18.74
Epoch 51 | Train: 18.29 | Val: 17.77
Epoch 52 | Train: 18.31 | Val: 17.78
Epoch 53 | Train: 17.85 | Val: 17.28
Epoch 54 | Train: 17.80 | Val: 19.22
Epoch 55 | Train: 17.86 | Val: 17.13
Epoch 56 | Train: 17.27 | Val: 18.16
Epoch 57 | Train: 17.21 | Val: 19.09
Epoch 58 | Train: 17.23 | Val: 18.96
Epoch 59 | Train: 16.67 | Val: 16.29
Epoch 60 | Train: 16.72 | Val: 17.05
Epoch 61 | Train: 16.47 | Val: 16.47
Epoch 62 | Train: 16.34 | Val: 18.09
Epoch 63 | Train: 16.27 | Val: 16.48
Epoch 64 | Train: 16.16 | Val: 16.66
Early stopping en epoch 64

Entrenando modelo [64, 32, 16] con lr=0.0005
Epoch 1 | Train: 1076.90 | Val: 569.05
Epoch 2 | Train: 504.40 | Val: 428.25
Epoch 3 | Train: 346.76 | Val: 290.88
Epoch 4 | Train: 247.15 | Val: 211.73
Epoch 5 | Train: 185.99 | Val: 164.56
Epoch 6 | Train: 142.86 | Val: 124.87
Epoch 7 | Train: 109.33 | Val: 98.34
Epoch 8 | Train: 88.60 | Val: 82.09
Epoch 9 | Train: 75.35 | Val: 70.72
Epoch 10 | Train: 66.01 | Val: 62.21
Epoch 11 | Train: 60.23 | Val: 62.31
Epoch 12 | Train: 56.33 | Val: 54.75
Epoch 13 | Train: 52.57 | Val: 51.90
Epoch 14 | Train: 49.45 | Val: 49.86
Epoch 15 | Train: 46.30 | Val: 44.62
Epoch 16 | Train: 43.28 | Val: 41.81
Epoch 17 | Train: 39.93 | Val: 37.74
Epoch 18 | Train: 35.47 | Val: 33.37
Epoch 19 | Train: 31.94 | Val: 32.32
Epoch 20 | Train: 29.12 | Val: 28.01
Epoch 21 | Train: 26.26 | Val: 24.92
Epoch 22 | Train: 23.42 | Val: 22.24
Epoch 23 | Train: 21.21 | Val: 20.59
Epoch 24 | Train: 19.51 | Val: 19.32
Epoch 25 | Train: 17.91 | Val: 16.90
Epoch 26 | Train: 16.04 | Val: 15.44
Epoch 27 | Train: 14.68 | Val: 13.59
Epoch 28 | Train: 13.65 | Val: 13.08
Epoch 29 | Train: 12.74 | Val: 12.83
Epoch 30 | Train: 11.88 | Val: 11.93
Epoch 31 | Train: 10.99 | Val: 10.71
Epoch 32 | Train: 10.48 | Val: 10.20
Epoch 33 | Train: 9.79 | Val: 9.49
Epoch 34 | Train: 9.41 | Val: 9.01
Epoch 35 | Train: 8.95 | Val: 8.85
Epoch 36 | Train: 8.53 | Val: 8.51
Epoch 37 | Train: 7.83 | Val: 7.16
Epoch 38 | Train: 7.39 | Val: 7.04
Epoch 39 | Train: 7.02 | Val: 6.96
Epoch 40 | Train: 6.71 | Val: 6.43
Epoch 41 | Train: 6.49 | Val: 6.50
Epoch 42 | Train: 6.27 | Val: 6.10
Epoch 43 | Train: 6.05 | Val: 6.14
Epoch 44 | Train: 5.81 | Val: 5.99
Epoch 45 | Train: 5.64 | Val: 5.32
Epoch 46 | Train: 5.53 | Val: 5.67
Epoch 47 | Train: 5.30 | Val: 5.53
Epoch 48 | Train: 5.09 | Val: 5.09
Epoch 49 | Train: 5.02 | Val: 5.72
Epoch 50 | Train: 4.94 | Val: 4.81
Epoch 51 | Train: 4.75 | Val: 4.79
Epoch 52 | Train: 4.70 | Val: 5.83
Epoch 53 | Train: 4.59 | Val: 5.77
Epoch 54 | Train: 4.57 | Val: 4.61
Epoch 55 | Train: 4.35 | Val: 4.29
Epoch 56 | Train: 4.42 | Val: 5.06
Epoch 57 | Train: 4.30 | Val: 5.92
Epoch 58 | Train: 4.33 | Val: 5.16
Epoch 59 | Train: 4.20 | Val: 4.52
Epoch 60 | Train: 4.11 | Val: 4.25
Epoch 61 | Train: 4.13 | Val: 3.98
Epoch 62 | Train: 4.04 | Val: 3.89
Epoch 63 | Train: 3.94 | Val: 4.10
Epoch 64 | Train: 3.98 | Val: 3.92
Epoch 65 | Train: 4.05 | Val: 6.70
Epoch 66 | Train: 3.90 | Val: 4.19
Epoch 67 | Train: 3.85 | Val: 3.91
Early stopping en epoch 67

Entrenando modelo [128, 64, 32] con lr=0.001
Epoch 1 | Train: 740.22 | Val: 416.26
Epoch 2 | Train: 244.45 | Val: 138.16
Epoch 3 | Train: 89.00 | Val: 60.74
Epoch 4 | Train: 46.15 | Val: 37.32
Epoch 5 | Train: 30.95 | Val: 25.40
Epoch 6 | Train: 21.78 | Val: 18.02
Epoch 7 | Train: 15.46 | Val: 16.36
Epoch 8 | Train: 11.55 | Val: 9.70
Epoch 9 | Train: 9.16 | Val: 7.88
Epoch 10 | Train: 7.71 | Val: 7.44
Epoch 11 | Train: 6.71 | Val: 5.95
Epoch 12 | Train: 6.00 | Val: 5.93
Epoch 13 | Train: 5.27 | Val: 5.38
Epoch 14 | Train: 4.84 | Val: 7.75
Epoch 15 | Train: 4.42 | Val: 4.49
Epoch 16 | Train: 4.12 | Val: 4.65
Epoch 17 | Train: 4.01 | Val: 3.56
Epoch 18 | Train: 3.82 | Val: 4.21
Epoch 19 | Train: 3.49 | Val: 3.25
Epoch 20 | Train: 3.16 | Val: 3.01
Epoch 21 | Train: 3.15 | Val: 4.48
Epoch 22 | Train: 3.08 | Val: 2.80
Epoch 23 | Train: 2.75 | Val: 3.26
Epoch 24 | Train: 2.82 | Val: 2.63
Epoch 25 | Train: 2.62 | Val: 2.19
Epoch 26 | Train: 2.50 | Val: 2.73
Epoch 27 | Train: 2.49 | Val: 2.11
Epoch 28 | Train: 2.41 | Val: 2.22
Epoch 29 | Train: 2.41 | Val: 2.48
Epoch 30 | Train: 2.55 | Val: 2.25
Epoch 31 | Train: 2.18 | Val: 1.99
Epoch 32 | Train: 2.16 | Val: 2.74
Epoch 33 | Train: 2.18 | Val: 2.43
Epoch 34 | Train: 2.00 | Val: 2.21
Epoch 35 | Train: 2.08 | Val: 2.28
Epoch 36 | Train: 2.02 | Val: 2.22
Early stopping en epoch 36

Entrenando modelo [128, 64, 32] con lr=0.0005
Epoch 1 | Train: 878.09 | Val: 484.38
Epoch 2 | Train: 354.51 | Val: 254.29
Epoch 3 | Train: 201.63 | Val: 160.86
Epoch 4 | Train: 126.05 | Val: 101.34
Epoch 5 | Train: 85.63 | Val: 73.34
Epoch 6 | Train: 62.83 | Val: 54.36
Epoch 7 | Train: 47.83 | Val: 42.48
Epoch 8 | Train: 38.69 | Val: 35.11
Epoch 9 | Train: 31.92 | Val: 29.01
Epoch 10 | Train: 27.40 | Val: 26.97
Epoch 11 | Train: 24.07 | Val: 22.17
Epoch 12 | Train: 21.28 | Val: 20.51
Epoch 13 | Train: 19.23 | Val: 17.39
Epoch 14 | Train: 17.15 | Val: 17.44
Epoch 15 | Train: 15.53 | Val: 14.43
Epoch 16 | Train: 14.13 | Val: 13.09
Epoch 17 | Train: 13.07 | Val: 11.98
Epoch 18 | Train: 11.45 | Val: 10.41
Epoch 19 | Train: 10.14 | Val: 9.78
Epoch 20 | Train: 9.04 | Val: 8.73
Epoch 21 | Train: 8.08 | Val: 9.29
Epoch 22 | Train: 7.52 | Val: 6.98
Epoch 23 | Train: 6.97 | Val: 7.48
Epoch 24 | Train: 6.50 | Val: 6.37
Epoch 25 | Train: 6.03 | Val: 6.50
Epoch 26 | Train: 5.72 | Val: 6.04
Epoch 27 | Train: 5.44 | Val: 6.25
Epoch 28 | Train: 5.09 | Val: 5.87
Epoch 29 | Train: 4.86 | Val: 5.06
Epoch 30 | Train: 4.66 | Val: 5.16
Epoch 31 | Train: 4.52 | Val: 4.30
Epoch 32 | Train: 4.39 | Val: 5.11
Epoch 33 | Train: 4.11 | Val: 5.03
Epoch 34 | Train: 4.17 | Val: 5.16
Epoch 35 | Train: 4.05 | Val: 4.57
Epoch 36 | Train: 3.98 | Val: 4.38
Early stopping en epoch 36

Entrenando modelo [256, 128, 64] con lr=0.001
Epoch 1 | Train: 571.54 | Val: 239.19
Epoch 2 | Train: 96.53 | Val: 36.58
Epoch 3 | Train: 26.58 | Val: 17.07
Epoch 4 | Train: 8.85 | Val: 4.17
Epoch 5 | Train: 3.56 | Val: 3.08
Epoch 6 | Train: 3.03 | Val: 2.99
Epoch 7 | Train: 2.97 | Val: 2.59
Epoch 8 | Train: 2.38 | Val: 2.36
Epoch 9 | Train: 2.31 | Val: 2.05
Epoch 10 | Train: 2.08 | Val: 2.04
Epoch 11 | Train: 2.12 | Val: 1.83
Epoch 12 | Train: 2.18 | Val: 3.27
Epoch 13 | Train: 2.04 | Val: 2.05
Epoch 14 | Train: 1.91 | Val: 1.86
Epoch 15 | Train: 1.77 | Val: 1.83
Epoch 16 | Train: 2.28 | Val: 1.64
Epoch 17 | Train: 1.67 | Val: 1.73
Epoch 18 | Train: 1.65 | Val: 3.72
Epoch 19 | Train: 1.68 | Val: 1.60
Epoch 20 | Train: 1.72 | Val: 1.65
Epoch 21 | Train: 1.58 | Val: 1.54
Epoch 22 | Train: 1.57 | Val: 1.69
Epoch 23 | Train: 1.60 | Val: 1.65
Epoch 24 | Train: 1.87 | Val: 1.46
Epoch 25 | Train: 1.53 | Val: 1.46
Epoch 26 | Train: 1.47 | Val: 1.48
Epoch 27 | Train: 1.52 | Val: 2.59
Epoch 28 | Train: 1.54 | Val: 2.14
Epoch 29 | Train: 1.50 | Val: 1.84
Early stopping en epoch 29

Entrenando modelo [256, 128, 64] con lr=0.0005
Epoch 1 | Train: 732.84 | Val: 436.38
Epoch 2 | Train: 290.51 | Val: 185.65
Epoch 3 | Train: 119.08 | Val: 76.02
Epoch 4 | Train: 54.09 | Val: 41.12
Epoch 5 | Train: 33.02 | Val: 25.62
Epoch 6 | Train: 22.45 | Val: 18.49
Epoch 7 | Train: 17.07 | Val: 14.95
Epoch 8 | Train: 13.78 | Val: 12.46
Epoch 9 | Train: 11.09 | Val: 10.38
Epoch 10 | Train: 9.23 | Val: 9.01
Epoch 11 | Train: 7.89 | Val: 7.12
Epoch 12 | Train: 6.82 | Val: 6.57
Epoch 13 | Train: 5.99 | Val: 5.84
Epoch 14 | Train: 5.44 | Val: 5.64
Epoch 15 | Train: 5.07 | Val: 5.08
Epoch 16 | Train: 4.91 | Val: 5.84
Epoch 17 | Train: 4.39 | Val: 4.07
Epoch 18 | Train: 4.22 | Val: 4.41
Epoch 19 | Train: 3.90 | Val: 3.70
Epoch 20 | Train: 3.65 | Val: 4.85
Epoch 21 | Train: 3.60 | Val: 3.69
Epoch 22 | Train: 3.38 | Val: 3.50
Epoch 23 | Train: 3.25 | Val: 3.85
Epoch 24 | Train: 3.06 | Val: 3.90
Epoch 25 | Train: 2.86 | Val: 2.69
Epoch 26 | Train: 2.78 | Val: 2.65
Epoch 27 | Train: 2.71 | Val: 2.84
Epoch 28 | Train: 2.66 | Val: 2.26
Epoch 29 | Train: 2.34 | Val: 2.23
Epoch 30 | Train: 2.40 | Val: 2.26
Epoch 31 | Train: 2.34 | Val: 2.48
Epoch 32 | Train: 2.27 | Val: 2.22
Epoch 33 | Train: 2.40 | Val: 2.31
Epoch 34 | Train: 2.15 | Val: 1.87
Epoch 35 | Train: 2.11 | Val: 2.29
Epoch 36 | Train: 1.99 | Val: 2.31
Epoch 37 | Train: 2.03 | Val: 1.92
Epoch 38 | Train: 1.91 | Val: 1.97
Epoch 39 | Train: 1.96 | Val: 1.99
Early stopping en epoch 39

In [111]:
for arch in arquitecturas:
    for lr in learning_rates:
        for dropout in dropouts:   
            
            model = PVModelV2(arch, dropout=dropout)
            
            print(f"\nEntrenando modelo {arch} | lr={lr} | dropout={dropout}")
            
            train_model(arch, lr, epochs, model)

Entrenando modelo [64, 32, 16] | lr=0.001 | dropout=0.1
Epoch 1 | Train: 1749.05 | Val: 879.97
Epoch 2 | Train: 401.29 | Val: 108.48
Epoch 3 | Train: 155.66 | Val: 64.96
Epoch 4 | Train: 135.01 | Val: 61.31
Epoch 5 | Train: 121.99 | Val: 43.83
Epoch 6 | Train: 112.01 | Val: 40.40
Epoch 7 | Train: 104.86 | Val: 30.23
Epoch 8 | Train: 97.67 | Val: 29.40
Epoch 9 | Train: 93.84 | Val: 24.24
Epoch 10 | Train: 89.35 | Val: 24.73
Epoch 11 | Train: 86.85 | Val: 21.37
Epoch 12 | Train: 84.70 | Val: 17.78
Epoch 13 | Train: 81.29 | Val: 18.82
Epoch 14 | Train: 80.09 | Val: 20.07
Epoch 15 | Train: 78.90 | Val: 15.88
Epoch 16 | Train: 78.71 | Val: 16.36
Epoch 17 | Train: 77.22 | Val: 15.74
Epoch 18 | Train: 72.68 | Val: 17.06
Epoch 19 | Train: 74.87 | Val: 12.34
Epoch 20 | Train: 72.04 | Val: 12.87
Epoch 21 | Train: 71.34 | Val: 13.97
Epoch 22 | Train: 71.40 | Val: 13.85
Epoch 23 | Train: 69.24 | Val: 12.65
Epoch 24 | Train: 69.47 | Val: 13.40
Early stopping en epoch 24

Entrenando modelo [64, 32, 16] | lr=0.001 | dropout=0.2
Epoch 1 | Train: 1780.16 | Val: 869.11
Epoch 2 | Train: 419.33 | Val: 126.18
Epoch 3 | Train: 201.49 | Val: 89.84
Epoch 4 | Train: 180.20 | Val: 69.44
Epoch 5 | Train: 169.21 | Val: 50.88
Epoch 6 | Train: 159.50 | Val: 52.06
Epoch 7 | Train: 153.10 | Val: 48.84
Epoch 8 | Train: 153.60 | Val: 46.05
Epoch 9 | Train: 148.38 | Val: 56.88
Epoch 10 | Train: 145.22 | Val: 41.34
Epoch 11 | Train: 142.48 | Val: 46.08
Epoch 12 | Train: 142.02 | Val: 41.06
Epoch 13 | Train: 139.46 | Val: 39.75
Epoch 14 | Train: 135.98 | Val: 38.82
Epoch 15 | Train: 134.01 | Val: 34.57
Epoch 16 | Train: 134.16 | Val: 34.28
Epoch 17 | Train: 132.47 | Val: 41.88
Epoch 18 | Train: 131.49 | Val: 30.09
Epoch 19 | Train: 131.14 | Val: 35.05
Epoch 20 | Train: 128.12 | Val: 33.27
Epoch 21 | Train: 126.90 | Val: 30.76
Epoch 22 | Train: 126.45 | Val: 42.09
Epoch 23 | Train: 124.63 | Val: 35.86
Early stopping en epoch 23

Entrenando modelo [64, 32, 16] | lr=0.0005 | dropout=0.1
Epoch 1 | Train: 2167.01 | Val: 1904.65
Epoch 2 | Train: 1374.48 | Val: 884.07
Epoch 3 | Train: 561.43 | Val: 263.02
Epoch 4 | Train: 224.56 | Val: 119.24
Epoch 5 | Train: 151.08 | Val: 74.34
Epoch 6 | Train: 133.80 | Val: 57.13
Epoch 7 | Train: 125.40 | Val: 53.53
Epoch 8 | Train: 121.05 | Val: 46.76
Epoch 9 | Train: 114.08 | Val: 42.02
Epoch 10 | Train: 108.63 | Val: 37.50
Epoch 11 | Train: 104.37 | Val: 36.36
Epoch 12 | Train: 101.66 | Val: 36.08
Epoch 13 | Train: 98.79 | Val: 32.96
Epoch 14 | Train: 96.23 | Val: 31.31
Epoch 15 | Train: 93.59 | Val: 26.23
Epoch 16 | Train: 89.35 | Val: 24.67
Epoch 17 | Train: 86.40 | Val: 22.87
Epoch 18 | Train: 84.90 | Val: 18.85
Epoch 19 | Train: 83.05 | Val: 20.75
Epoch 20 | Train: 81.44 | Val: 18.02
Epoch 21 | Train: 80.65 | Val: 19.54
Epoch 22 | Train: 75.93 | Val: 17.78
Epoch 23 | Train: 75.16 | Val: 17.00
Epoch 24 | Train: 74.03 | Val: 19.37
Epoch 25 | Train: 73.48 | Val: 24.04
Epoch 26 | Train: 72.01 | Val: 19.52
Epoch 27 | Train: 72.23 | Val: 16.44
Epoch 28 | Train: 73.26 | Val: 17.10
Epoch 29 | Train: 69.36 | Val: 16.79
Epoch 30 | Train: 69.84 | Val: 22.38
Epoch 31 | Train: 70.19 | Val: 19.86
Epoch 32 | Train: 69.59 | Val: 17.54
Early stopping en epoch 32

Entrenando modelo [64, 32, 16] | lr=0.0005 | dropout=0.2
Epoch 1 | Train: 2202.63 | Val: 1902.75
Epoch 2 | Train: 1426.71 | Val: 978.50
Epoch 3 | Train: 615.13 | Val: 313.59
Epoch 4 | Train: 270.16 | Val: 106.84
Epoch 5 | Train: 197.22 | Val: 76.71
Epoch 6 | Train: 181.39 | Val: 76.74
Epoch 7 | Train: 178.34 | Val: 62.03
Epoch 8 | Train: 169.94 | Val: 56.99
Epoch 9 | Train: 162.84 | Val: 49.10
Epoch 10 | Train: 158.33 | Val: 51.92
Epoch 11 | Train: 152.63 | Val: 35.05
Epoch 12 | Train: 146.48 | Val: 34.73
Epoch 13 | Train: 139.91 | Val: 36.61
Epoch 14 | Train: 140.12 | Val: 31.13
Epoch 15 | Train: 136.07 | Val: 28.91
Epoch 16 | Train: 132.72 | Val: 31.58
Epoch 17 | Train: 131.08 | Val: 30.10
Epoch 18 | Train: 128.63 | Val: 30.34
Epoch 19 | Train: 128.87 | Val: 27.39
Epoch 20 | Train: 126.67 | Val: 27.47
Epoch 21 | Train: 125.59 | Val: 30.75
Epoch 22 | Train: 124.53 | Val: 27.57
Epoch 23 | Train: 123.69 | Val: 25.29
Epoch 24 | Train: 123.34 | Val: 24.11
Epoch 25 | Train: 124.52 | Val: 22.46
Epoch 26 | Train: 120.83 | Val: 24.57
Epoch 27 | Train: 120.84 | Val: 25.48
Epoch 28 | Train: 119.70 | Val: 28.65
Epoch 29 | Train: 119.01 | Val: 28.17
Epoch 30 | Train: 119.37 | Val: 21.78
Epoch 31 | Train: 118.93 | Val: 25.45
Epoch 32 | Train: 118.01 | Val: 26.73
Epoch 33 | Train: 115.79 | Val: 20.30
Epoch 34 | Train: 115.04 | Val: 22.71
Epoch 35 | Train: 115.05 | Val: 23.27
Epoch 36 | Train: 115.16 | Val: 19.67
Epoch 37 | Train: 114.65 | Val: 22.33
Epoch 38 | Train: 113.47 | Val: 19.97
Epoch 39 | Train: 113.63 | Val: 22.52
Epoch 40 | Train: 113.68 | Val: 22.72
Epoch 41 | Train: 111.32 | Val: 20.48
Early stopping en epoch 41

Entrenando modelo [128, 64, 32] | lr=0.001 | dropout=0.1
Epoch 1 | Train: 1425.31 | Val: 291.14
Epoch 2 | Train: 184.22 | Val: 68.46
Epoch 3 | Train: 117.00 | Val: 45.45
Epoch 4 | Train: 98.26 | Val: 34.72
Epoch 5 | Train: 83.29 | Val: 32.48
Epoch 6 | Train: 73.99 | Val: 18.88
Epoch 7 | Train: 65.29 | Val: 18.96
Epoch 8 | Train: 62.74 | Val: 13.60
Epoch 9 | Train: 56.69 | Val: 13.62
Epoch 10 | Train: 56.33 | Val: 12.17
Epoch 11 | Train: 52.14 | Val: 9.70
Epoch 12 | Train: 49.09 | Val: 12.91
Epoch 13 | Train: 46.79 | Val: 7.91
Epoch 14 | Train: 47.19 | Val: 12.36
Epoch 15 | Train: 44.48 | Val: 7.16
Epoch 16 | Train: 42.49 | Val: 7.45
Epoch 17 | Train: 44.57 | Val: 8.89
Epoch 18 | Train: 39.10 | Val: 9.17
Epoch 19 | Train: 39.52 | Val: 8.70
Epoch 20 | Train: 40.08 | Val: 5.32
Epoch 21 | Train: 38.62 | Val: 4.93
Epoch 22 | Train: 38.55 | Val: 4.97
Epoch 23 | Train: 38.95 | Val: 7.99
Epoch 24 | Train: 37.11 | Val: 7.59
Epoch 25 | Train: 36.18 | Val: 6.96
Epoch 26 | Train: 36.81 | Val: 6.21
Early stopping en epoch 26

Entrenando modelo [128, 64, 32] | lr=0.001 | dropout=0.2
Epoch 1 | Train: 1401.86 | Val: 316.05
Epoch 2 | Train: 213.19 | Val: 68.84
Epoch 3 | Train: 140.75 | Val: 47.23
Epoch 4 | Train: 117.51 | Val: 31.66
Epoch 5 | Train: 104.17 | Val: 27.22
Epoch 6 | Train: 96.66 | Val: 16.85
Epoch 7 | Train: 88.57 | Val: 17.90
Epoch 8 | Train: 84.12 | Val: 12.56
Epoch 9 | Train: 79.72 | Val: 11.27
Epoch 10 | Train: 76.95 | Val: 14.32
Epoch 11 | Train: 72.70 | Val: 13.72
Epoch 12 | Train: 71.51 | Val: 9.55
Epoch 13 | Train: 70.59 | Val: 7.96
Epoch 14 | Train: 66.88 | Val: 11.67
Epoch 15 | Train: 66.03 | Val: 6.94
Epoch 16 | Train: 65.85 | Val: 6.31
Epoch 17 | Train: 65.74 | Val: 10.54
Epoch 18 | Train: 62.49 | Val: 6.84
Epoch 19 | Train: 63.80 | Val: 6.86
Epoch 20 | Train: 62.12 | Val: 6.43
Epoch 21 | Train: 61.36 | Val: 5.35
Epoch 22 | Train: 62.79 | Val: 6.39
Epoch 23 | Train: 60.78 | Val: 7.44
Epoch 24 | Train: 59.96 | Val: 5.61
Epoch 25 | Train: 59.04 | Val: 10.16
Epoch 26 | Train: 59.82 | Val: 5.52
Early stopping en epoch 26

Entrenando modelo [128, 64, 32] | lr=0.0005 | dropout=0.1
Epoch 1 | Train: 1961.75 | Val: 1401.05
Epoch 2 | Train: 786.35 | Val: 331.01
Epoch 3 | Train: 218.10 | Val: 79.67
Epoch 4 | Train: 130.53 | Val: 57.92
Epoch 5 | Train: 113.41 | Val: 39.40
Epoch 6 | Train: 100.54 | Val: 32.23
Epoch 7 | Train: 91.50 | Val: 30.17
Epoch 8 | Train: 82.32 | Val: 22.75
Epoch 9 | Train: 76.95 | Val: 19.71
Epoch 10 | Train: 72.04 | Val: 20.08
Epoch 11 | Train: 66.76 | Val: 12.75
Epoch 12 | Train: 62.49 | Val: 15.70
Epoch 13 | Train: 61.59 | Val: 10.69
Epoch 14 | Train: 59.90 | Val: 9.99
Epoch 15 | Train: 55.55 | Val: 13.26
Epoch 16 | Train: 55.26 | Val: 8.63
Epoch 17 | Train: 51.31 | Val: 9.90
Epoch 18 | Train: 50.49 | Val: 7.42
Epoch 19 | Train: 48.47 | Val: 7.64
Epoch 20 | Train: 47.57 | Val: 7.12
Epoch 21 | Train: 46.06 | Val: 8.63
Epoch 22 | Train: 45.80 | Val: 7.79
Epoch 23 | Train: 44.05 | Val: 7.70
Epoch 24 | Train: 44.27 | Val: 6.82
Epoch 25 | Train: 42.35 | Val: 5.07
Epoch 26 | Train: 42.67 | Val: 8.31
Epoch 27 | Train: 41.41 | Val: 5.14
Epoch 28 | Train: 41.62 | Val: 5.77
Epoch 29 | Train: 40.50 | Val: 6.82
Epoch 30 | Train: 39.89 | Val: 4.84
Epoch 31 | Train: 39.88 | Val: 6.88
Epoch 32 | Train: 38.84 | Val: 5.37
Epoch 33 | Train: 39.46 | Val: 4.32
Epoch 34 | Train: 36.68 | Val: 5.20
Epoch 35 | Train: 37.63 | Val: 8.03
Epoch 36 | Train: 36.73 | Val: 4.83
Epoch 37 | Train: 36.72 | Val: 4.35
Epoch 38 | Train: 36.23 | Val: 4.82
Early stopping en epoch 38

Entrenando modelo [128, 64, 32] | lr=0.0005 | dropout=0.2
Epoch 1 | Train: 2020.01 | Val: 1476.27
Epoch 2 | Train: 819.65 | Val: 308.83
Epoch 3 | Train: 255.13 | Val: 106.99
Epoch 4 | Train: 158.66 | Val: 53.13
Epoch 5 | Train: 135.60 | Val: 42.33
Epoch 6 | Train: 121.00 | Val: 32.96
Epoch 7 | Train: 113.89 | Val: 27.90
Epoch 8 | Train: 108.65 | Val: 23.74
Epoch 9 | Train: 101.01 | Val: 22.75
Epoch 10 | Train: 97.39 | Val: 17.99
Epoch 11 | Train: 92.21 | Val: 17.85
Epoch 12 | Train: 87.03 | Val: 17.50
Epoch 13 | Train: 84.15 | Val: 14.18
Epoch 14 | Train: 81.88 | Val: 12.05
Epoch 15 | Train: 80.09 | Val: 14.28
Epoch 16 | Train: 78.52 | Val: 10.24
Epoch 17 | Train: 76.23 | Val: 13.29
Epoch 18 | Train: 74.42 | Val: 15.26
Epoch 19 | Train: 72.00 | Val: 11.83
Epoch 20 | Train: 73.61 | Val: 9.71
Epoch 21 | Train: 70.79 | Val: 10.07
Epoch 22 | Train: 70.07 | Val: 7.52
Epoch 23 | Train: 70.08 | Val: 8.53
Epoch 24 | Train: 71.10 | Val: 12.27
Epoch 25 | Train: 68.34 | Val: 9.31
Epoch 26 | Train: 67.21 | Val: 9.29
Epoch 27 | Train: 65.95 | Val: 9.04
Early stopping en epoch 27

Entrenando modelo [256, 128, 64] | lr=0.001 | dropout=0.1
Epoch 1 | Train: 1033.06 | Val: 106.74
Epoch 2 | Train: 127.02 | Val: 53.77
Epoch 3 | Train: 94.21 | Val: 31.91
Epoch 4 | Train: 76.41 | Val: 29.21
Epoch 5 | Train: 65.81 | Val: 18.13
Epoch 6 | Train: 58.07 | Val: 16.96
Epoch 7 | Train: 51.13 | Val: 11.89
Epoch 8 | Train: 45.44 | Val: 10.65
Epoch 9 | Train: 41.93 | Val: 10.12
Epoch 10 | Train: 41.30 | Val: 11.21
Epoch 11 | Train: 36.69 | Val: 11.51
Epoch 12 | Train: 35.07 | Val: 7.17
Epoch 13 | Train: 33.15 | Val: 9.97
Epoch 14 | Train: 31.79 | Val: 5.04
Epoch 15 | Train: 30.70 | Val: 5.86
Epoch 16 | Train: 28.82 | Val: 8.26
Epoch 17 | Train: 28.84 | Val: 3.41
Epoch 18 | Train: 27.67 | Val: 7.00
Epoch 19 | Train: 28.03 | Val: 6.01
Epoch 20 | Train: 28.23 | Val: 4.31
Epoch 21 | Train: 24.50 | Val: 5.57
Epoch 22 | Train: 25.90 | Val: 3.13
Epoch 23 | Train: 25.20 | Val: 4.27
Epoch 24 | Train: 24.64 | Val: 3.93
Epoch 25 | Train: 25.51 | Val: 3.08
Epoch 26 | Train: 23.32 | Val: 3.37
Epoch 27 | Train: 24.53 | Val: 2.79
Epoch 28 | Train: 23.87 | Val: 3.59
Epoch 29 | Train: 22.25 | Val: 5.01
Epoch 30 | Train: 20.64 | Val: 4.29
Epoch 31 | Train: 22.01 | Val: 5.79
Epoch 32 | Train: 21.81 | Val: 3.84
Early stopping en epoch 32

Entrenando modelo [256, 128, 64] | lr=0.001 | dropout=0.2
Epoch 1 | Train: 997.28 | Val: 133.90
Epoch 2 | Train: 154.85 | Val: 56.41
Epoch 3 | Train: 114.01 | Val: 35.46
Epoch 4 | Train: 91.82 | Val: 22.11
Epoch 5 | Train: 74.11 | Val: 15.67
Epoch 6 | Train: 64.62 | Val: 15.38
Epoch 7 | Train: 60.09 | Val: 9.41
Epoch 8 | Train: 54.38 | Val: 12.39
Epoch 9 | Train: 51.01 | Val: 7.75
Epoch 10 | Train: 48.65 | Val: 7.28
Epoch 11 | Train: 48.96 | Val: 9.15
Epoch 12 | Train: 44.11 | Val: 5.33
Epoch 13 | Train: 43.58 | Val: 5.71
Epoch 14 | Train: 41.30 | Val: 5.23
Epoch 15 | Train: 42.88 | Val: 5.06
Epoch 16 | Train: 41.69 | Val: 5.01
Epoch 17 | Train: 39.59 | Val: 6.57
Epoch 18 | Train: 38.58 | Val: 4.79
Epoch 19 | Train: 38.08 | Val: 6.84
Epoch 20 | Train: 37.61 | Val: 3.62
Epoch 21 | Train: 36.74 | Val: 5.55
Epoch 22 | Train: 37.97 | Val: 4.07
Epoch 23 | Train: 36.61 | Val: 4.53
Epoch 24 | Train: 38.03 | Val: 4.66
Epoch 25 | Train: 36.38 | Val: 4.21
Early stopping en epoch 25

Entrenando modelo [256, 128, 64] | lr=0.0005 | dropout=0.1
Epoch 1 | Train: 1622.88 | Val: 671.20
Epoch 2 | Train: 308.68 | Val: 90.06
Epoch 3 | Train: 127.54 | Val: 57.34
Epoch 4 | Train: 108.14 | Val: 42.39
Epoch 5 | Train: 94.06 | Val: 36.17
Epoch 6 | Train: 84.62 | Val: 30.73
Epoch 7 | Train: 74.75 | Val: 24.78
Epoch 8 | Train: 70.24 | Val: 19.09
Epoch 9 | Train: 63.76 | Val: 18.84
Epoch 10 | Train: 58.46 | Val: 17.40
Epoch 11 | Train: 55.28 | Val: 12.14
Epoch 12 | Train: 51.26 | Val: 12.40
Epoch 13 | Train: 50.02 | Val: 9.56
Epoch 14 | Train: 44.10 | Val: 9.45
Epoch 15 | Train: 42.10 | Val: 10.78
Epoch 16 | Train: 41.23 | Val: 9.71
Epoch 17 | Train: 38.82 | Val: 5.17
Epoch 18 | Train: 37.91 | Val: 6.44
Epoch 19 | Train: 35.35 | Val: 9.86
Epoch 20 | Train: 33.76 | Val: 6.07
Epoch 21 | Train: 33.14 | Val: 4.52
Epoch 22 | Train: 32.79 | Val: 5.81
Epoch 23 | Train: 31.06 | Val: 5.80
Epoch 24 | Train: 30.86 | Val: 4.71
Epoch 25 | Train: 30.43 | Val: 5.02
Epoch 26 | Train: 29.15 | Val: 5.36
Early stopping en epoch 26

Entrenando modelo [256, 128, 64] | lr=0.0005 | dropout=0.2
Epoch 1 | Train: 1674.29 | Val: 738.05
Epoch 2 | Train: 359.46 | Val: 119.12
Epoch 3 | Train: 166.94 | Val: 79.08
Epoch 4 | Train: 136.96 | Val: 57.58
Epoch 5 | Train: 119.30 | Val: 48.00
Epoch 6 | Train: 103.83 | Val: 36.51
Epoch 7 | Train: 94.71 | Val: 31.30
Epoch 8 | Train: 87.22 | Val: 22.85
Epoch 9 | Train: 80.10 | Val: 17.60
Epoch 10 | Train: 75.17 | Val: 17.93
Epoch 11 | Train: 73.46 | Val: 18.74
Epoch 12 | Train: 68.14 | Val: 16.01
Epoch 13 | Train: 65.42 | Val: 11.95
Epoch 14 | Train: 62.29 | Val: 14.54
Epoch 15 | Train: 58.04 | Val: 13.61
Epoch 16 | Train: 57.28 | Val: 10.78
Epoch 17 | Train: 55.32 | Val: 9.56
Epoch 18 | Train: 53.66 | Val: 8.86
Epoch 19 | Train: 51.63 | Val: 8.69
Epoch 20 | Train: 50.76 | Val: 8.81
Epoch 21 | Train: 48.56 | Val: 7.74
Epoch 22 | Train: 47.53 | Val: 7.60
Epoch 23 | Train: 48.01 | Val: 7.29
Epoch 24 | Train: 48.61 | Val: 9.60
Epoch 25 | Train: 44.87 | Val: 6.66
Epoch 26 | Train: 44.90 | Val: 5.54
Epoch 27 | Train: 42.79 | Val: 7.50
Epoch 28 | Train: 44.48 | Val: 7.08
Epoch 29 | Train: 43.30 | Val: 7.52
Epoch 30 | Train: 40.50 | Val: 5.36
Epoch 31 | Train: 40.14 | Val: 5.47
Epoch 32 | Train: 41.26 | Val: 5.94
Epoch 33 | Train: 41.18 | Val: 6.21
Epoch 34 | Train: 39.09 | Val: 5.17
Epoch 35 | Train: 39.07 | Val: 5.57
Epoch 36 | Train: 37.81 | Val: 5.31
Epoch 37 | Train: 39.14 | Val: 5.67
Epoch 38 | Train: 38.63 | Val: 4.40
Epoch 39 | Train: 36.91 | Val: 4.70
Epoch 40 | Train: 37.64 | Val: 5.19
Epoch 41 | Train: 35.85 | Val: 8.90
Epoch 42 | Train: 36.20 | Val: 3.92
Epoch 43 | Train: 35.15 | Val: 3.66
Epoch 44 | Train: 35.55 | Val: 4.42
Epoch 45 | Train: 36.16 | Val: 5.32
Epoch 46 | Train: 35.45 | Val: 5.33
Epoch 47 | Train: 34.04 | Val: 4.05
Epoch 48 | Train: 34.17 | Val: 4.56
Early stopping en epoch 48

# MODELOS SIMPLES

In [112]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Entrenar modelo
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Predicción
y_pred = lr_model.predict(X_val)

# Métricas
mse = mean_squared_error(y_val, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_val, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

MSE: 576.3045725256211
RMSE: 24.006344422373456
R2: 0.5934330172716631

In [113]:
y_pred_nn = model(X_val_tensor).detach().numpy()

In [114]:
mean_squared_error(y_val, y_pred_nn)

4.569985740959549

In [115]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Modelo
model = XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

# Entrenar
model.fit(X_train, y_train)

# Predecir
y_pred = model.predict(X_val)

# Métricas
mse = mean_squared_error(y_val, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_val, y_pred)

print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

MSE: 2.57751123635138
RMSE: 1.6054629352156904
R2: 0.9981816369047373

# 4. FEATURE ENGENIERING

In [116]:
corr = df_model.corr(numeric_only=True)
corr["Pmp (W)"].sort_values(ascending=False)

Pmp (W)                                       1.000000
POA irradiance CMP22 pyranometer (W/m2)       0.748333
PV module back surface temperature (degC)     0.561800
Direct normal irradiance (W/m2)               0.068805
Global horizontal irradiance (W/m2)           0.057096
Precipitation (mm) accumulated daily total   -0.018312
Dry bulb temperature (degC)                  -0.019508
Diffuse horizontal irradiance (W/m2)         -0.023923
Atmospheric pressure (mb)                    -0.031497
Relative humidity (%RH)                      -0.033575
parque_enc                                   -0.036538
panel_enc                                    -0.179015
Name: Pmp (W), dtype: float64

In [117]:
df_model["physical_model"] = (
    df_model["POA irradiance CMP22 pyranometer (W/m2)"] *
    (1 - 0.004 * (df_model["PV module back surface temperature (degC)"] - 25))
)

In [118]:
df_model = df_model[[
    "POA irradiance CMP22 pyranometer (W/m2)",
    "PV module back surface temperature (degC)",
    "physical_model",
    "Pmp (W)"
]]

In [119]:
X = df_model.drop(columns=["Pmp (W)"])
y = df_model["Pmp (W)"]

In [120]:
from sklearn.model_selection import train_test_split

# Primero separar test (20%)
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Luego separar val del resto (20% del total = 25% de train_val)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42
)

# Resultado: 60% train, 20% val, 20% test
print(X_train.shape, X_val.shape, X_test.shape)

(615359, 3) (205120, 3) (205120, 3)

In [121]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.fit_transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [122]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(
    train_dataset,
    batch_size=1024,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=1024,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1024
)

In [123]:
for arch in arquitecturas:
    for lr in learning_rates:
        model = PVModel(arch)
        print(f"\nEntrenando modelo {arch} con lr={lr}")
        train_model(arch, lr, epochs,model)

Entrenando modelo [64, 32, 16] con lr=0.001
Epoch 1 | Train: 831.11 | Val: 469.28
Epoch 2 | Train: 356.33 | Val: 304.37
Epoch 3 | Train: 269.90 | Val: 237.96
Epoch 4 | Train: 192.68 | Val: 153.05
Epoch 5 | Train: 124.72 | Val: 104.05
Epoch 6 | Train: 88.79 | Val: 77.27
Epoch 7 | Train: 70.60 | Val: 64.29
Epoch 8 | Train: 62.22 | Val: 57.51
Epoch 9 | Train: 55.98 | Val: 53.70
Epoch 10 | Train: 51.60 | Val: 49.95
Epoch 11 | Train: 48.20 | Val: 45.22
Epoch 12 | Train: 45.24 | Val: 45.83
Epoch 13 | Train: 43.49 | Val: 41.66
Epoch 14 | Train: 41.55 | Val: 38.84
Epoch 15 | Train: 39.24 | Val: 38.53
Epoch 16 | Train: 36.37 | Val: 34.78
Epoch 17 | Train: 33.96 | Val: 34.09
Epoch 18 | Train: 32.36 | Val: 30.75
Epoch 19 | Train: 29.91 | Val: 27.83
Epoch 20 | Train: 27.84 | Val: 28.25
Epoch 21 | Train: 26.12 | Val: 24.92
Epoch 22 | Train: 24.58 | Val: 22.69
Epoch 23 | Train: 23.23 | Val: 21.92
Epoch 24 | Train: 21.14 | Val: 22.92
Epoch 25 | Train: 20.13 | Val: 21.81
Epoch 26 | Train: 19.35 | Val: 20.00
Epoch 27 | Train: 18.05 | Val: 16.51
Epoch 28 | Train: 17.28 | Val: 16.90
Epoch 29 | Train: 16.42 | Val: 15.34
Epoch 30 | Train: 15.78 | Val: 15.54
Epoch 31 | Train: 15.33 | Val: 16.84
Epoch 32 | Train: 14.86 | Val: 14.04
Epoch 33 | Train: 14.38 | Val: 13.40
Epoch 34 | Train: 13.77 | Val: 12.52
Epoch 35 | Train: 13.19 | Val: 12.50
Epoch 36 | Train: 12.88 | Val: 14.06
Epoch 37 | Train: 12.41 | Val: 12.02
Epoch 38 | Train: 12.24 | Val: 11.01
Epoch 39 | Train: 11.64 | Val: 11.23
Epoch 40 | Train: 11.44 | Val: 12.97
Epoch 41 | Train: 10.93 | Val: 10.08
Epoch 42 | Train: 10.41 | Val: 11.90
Epoch 43 | Train: 10.68 | Val: 12.20
Epoch 44 | Train: 9.74 | Val: 9.20
Epoch 45 | Train: 9.39 | Val: 11.10
Epoch 46 | Train: 9.05 | Val: 8.09
Epoch 47 | Train: 8.82 | Val: 9.07
Epoch 48 | Train: 8.61 | Val: 10.99
Epoch 49 | Train: 8.46 | Val: 9.51
Epoch 50 | Train: 8.09 | Val: 7.26
Epoch 51 | Train: 7.66 | Val: 7.61
Epoch 52 | Train: 7.71 | Val: 7.21
Epoch 53 | Train: 7.55 | Val: 8.84
Epoch 54 | Train: 6.96 | Val: 6.68
Epoch 55 | Train: 7.10 | Val: 8.02
Epoch 56 | Train: 6.74 | Val: 6.18
Epoch 57 | Train: 6.65 | Val: 11.52
Epoch 58 | Train: 6.64 | Val: 5.77
Epoch 59 | Train: 6.26 | Val: 5.98
Epoch 60 | Train: 6.19 | Val: 10.40
Epoch 61 | Train: 6.08 | Val: 6.60
Epoch 62 | Train: 6.00 | Val: 6.10
Epoch 63 | Train: 6.14 | Val: 7.77
Early stopping en epoch 63

Entrenando modelo [64, 32, 16] con lr=0.0005
Epoch 1 | Train: 1152.13 | Val: 561.22
Epoch 2 | Train: 522.80 | Val: 487.66
Epoch 3 | Train: 406.19 | Val: 323.52
Epoch 4 | Train: 251.71 | Val: 199.50
Epoch 5 | Train: 167.06 | Val: 143.99
Epoch 6 | Train: 127.10 | Val: 114.29
Epoch 7 | Train: 103.45 | Val: 95.88
Epoch 8 | Train: 88.49 | Val: 83.14
Epoch 9 | Train: 77.82 | Val: 74.86
Epoch 10 | Train: 69.61 | Val: 66.85
Epoch 11 | Train: 63.37 | Val: 60.87
Epoch 12 | Train: 58.74 | Val: 56.38
Epoch 13 | Train: 54.98 | Val: 53.89
Epoch 14 | Train: 51.89 | Val: 50.27
Epoch 15 | Train: 49.00 | Val: 47.22
Epoch 16 | Train: 46.54 | Val: 46.06
Epoch 17 | Train: 44.80 | Val: 44.24
Epoch 18 | Train: 43.34 | Val: 44.19
Epoch 19 | Train: 42.50 | Val: 41.34
Epoch 20 | Train: 41.32 | Val: 40.83
Epoch 21 | Train: 40.59 | Val: 40.06
Epoch 22 | Train: 39.71 | Val: 39.54
Epoch 23 | Train: 39.27 | Val: 39.34
Epoch 24 | Train: 38.46 | Val: 37.89
Epoch 25 | Train: 37.79 | Val: 37.22
Epoch 26 | Train: 37.33 | Val: 36.86
Epoch 27 | Train: 36.92 | Val: 37.43
Epoch 28 | Train: 36.21 | Val: 36.43
Epoch 29 | Train: 35.90 | Val: 36.36
Epoch 30 | Train: 35.34 | Val: 35.21
Epoch 31 | Train: 34.95 | Val: 35.20
Epoch 32 | Train: 34.49 | Val: 34.12
Epoch 33 | Train: 34.28 | Val: 34.08
Epoch 34 | Train: 33.77 | Val: 33.61
Epoch 35 | Train: 33.50 | Val: 33.42
Epoch 36 | Train: 33.10 | Val: 32.69
Epoch 37 | Train: 32.69 | Val: 33.50
Epoch 38 | Train: 32.39 | Val: 31.90
Epoch 39 | Train: 31.92 | Val: 32.57
Epoch 40 | Train: 31.61 | Val: 31.64
Epoch 41 | Train: 31.24 | Val: 30.83
Epoch 42 | Train: 30.68 | Val: 30.54
Epoch 43 | Train: 30.21 | Val: 29.87
Epoch 44 | Train: 29.81 | Val: 29.73
Epoch 45 | Train: 29.40 | Val: 30.03
Epoch 46 | Train: 28.92 | Val: 28.54
Epoch 47 | Train: 28.41 | Val: 28.55
Epoch 48 | Train: 27.93 | Val: 27.80
Epoch 49 | Train: 27.48 | Val: 27.14
Epoch 50 | Train: 26.95 | Val: 26.96
Epoch 51 | Train: 26.33 | Val: 26.01
Epoch 52 | Train: 26.06 | Val: 26.49
Epoch 53 | Train: 25.43 | Val: 25.32
Epoch 54 | Train: 24.80 | Val: 24.11
Epoch 55 | Train: 24.07 | Val: 24.15
Epoch 56 | Train: 23.18 | Val: 22.71
Epoch 57 | Train: 21.26 | Val: 20.25
Epoch 58 | Train: 18.90 | Val: 18.48
Epoch 59 | Train: 17.52 | Val: 17.08
Epoch 60 | Train: 16.35 | Val: 15.82
Epoch 61 | Train: 15.38 | Val: 15.67
Epoch 62 | Train: 14.45 | Val: 13.68
Epoch 63 | Train: 13.73 | Val: 13.18
Epoch 64 | Train: 13.05 | Val: 13.00
Epoch 65 | Train: 12.57 | Val: 12.10
Epoch 66 | Train: 12.00 | Val: 12.36
Epoch 67 | Train: 11.66 | Val: 11.06
Epoch 68 | Train: 11.30 | Val: 10.95
Epoch 69 | Train: 10.89 | Val: 10.86
Epoch 70 | Train: 10.64 | Val: 11.78
Epoch 71 | Train: 10.20 | Val: 10.07
Epoch 72 | Train: 9.90 | Val: 10.14
Epoch 73 | Train: 9.69 | Val: 9.35
Epoch 74 | Train: 9.39 | Val: 9.44
Epoch 75 | Train: 9.00 | Val: 9.15
Epoch 76 | Train: 8.82 | Val: 8.96
Epoch 77 | Train: 8.68 | Val: 8.54
Epoch 78 | Train: 8.45 | Val: 10.05
Epoch 79 | Train: 8.40 | Val: 8.30
Epoch 80 | Train: 8.25 | Val: 8.25
Epoch 81 | Train: 7.95 | Val: 8.97
Epoch 82 | Train: 7.76 | Val: 8.24
Epoch 83 | Train: 7.67 | Val: 9.03
Epoch 84 | Train: 7.43 | Val: 8.33
Epoch 85 | Train: 7.33 | Val: 7.38
Epoch 86 | Train: 7.29 | Val: 7.63
Epoch 87 | Train: 7.15 | Val: 8.10
Epoch 88 | Train: 7.03 | Val: 7.93
Epoch 89 | Train: 6.92 | Val: 7.06
Epoch 90 | Train: 6.78 | Val: 7.16
Epoch 91 | Train: 6.65 | Val: 6.74
Epoch 92 | Train: 6.65 | Val: 6.65
Epoch 93 | Train: 6.50 | Val: 6.96
Epoch 94 | Train: 6.44 | Val: 6.25
Epoch 95 | Train: 6.39 | Val: 6.73
Epoch 96 | Train: 6.31 | Val: 6.43
Epoch 97 | Train: 6.11 | Val: 6.43
Epoch 98 | Train: 6.17 | Val: 6.26
Epoch 99 | Train: 5.98 | Val: 5.87
Epoch 100 | Train: 5.99 | Val: 6.47

Entrenando modelo [128, 64, 32] con lr=0.001
Epoch 1 | Train: 705.71 | Val: 348.12
Epoch 2 | Train: 221.79 | Val: 132.83
Epoch 3 | Train: 85.24 | Val: 56.53
Epoch 4 | Train: 42.93 | Val: 32.96
Epoch 5 | Train: 28.47 | Val: 24.44
Epoch 6 | Train: 21.99 | Val: 20.45
Epoch 7 | Train: 16.77 | Val: 14.30
Epoch 8 | Train: 12.42 | Val: 10.22
Epoch 9 | Train: 9.40 | Val: 8.40
Epoch 10 | Train: 7.81 | Val: 7.24
Epoch 11 | Train: 6.33 | Val: 5.66
Epoch 12 | Train: 5.67 | Val: 4.90
Epoch 13 | Train: 4.94 | Val: 4.43
Epoch 14 | Train: 4.37 | Val: 4.22
Epoch 15 | Train: 4.08 | Val: 4.70
Epoch 16 | Train: 3.88 | Val: 3.61
Epoch 17 | Train: 3.51 | Val: 3.23
Epoch 18 | Train: 3.41 | Val: 3.88
Epoch 19 | Train: 3.16 | Val: 3.59
Epoch 20 | Train: 2.98 | Val: 2.97
Epoch 21 | Train: 2.86 | Val: 3.81
Epoch 22 | Train: 2.72 | Val: 2.54
Epoch 23 | Train: 2.58 | Val: 2.92
Epoch 24 | Train: 2.66 | Val: 2.49
Epoch 25 | Train: 2.58 | Val: 2.32
Epoch 26 | Train: 2.36 | Val: 2.22
Epoch 27 | Train: 2.49 | Val: 2.21
Epoch 28 | Train: 2.43 | Val: 2.10
Epoch 29 | Train: 2.21 | Val: 2.19
Epoch 30 | Train: 2.20 | Val: 1.99
Epoch 31 | Train: 2.15 | Val: 1.94
Epoch 32 | Train: 2.13 | Val: 2.22
Epoch 33 | Train: 2.08 | Val: 2.22
Epoch 34 | Train: 2.16 | Val: 1.77
Epoch 35 | Train: 2.10 | Val: 2.28
Epoch 36 | Train: 2.09 | Val: 1.90
Epoch 37 | Train: 1.98 | Val: 2.95
Epoch 38 | Train: 2.02 | Val: 1.78
Epoch 39 | Train: 1.98 | Val: 1.96
Early stopping en epoch 39

Entrenando modelo [128, 64, 32] con lr=0.0005
Epoch 1 | Train: 881.52 | Val: 500.91
Epoch 2 | Train: 364.79 | Val: 267.82
Epoch 3 | Train: 216.55 | Val: 177.49
Epoch 4 | Train: 143.61 | Val: 117.14
Epoch 5 | Train: 96.30 | Val: 79.18
Epoch 6 | Train: 67.92 | Val: 59.06
Epoch 7 | Train: 53.05 | Val: 46.45
Epoch 8 | Train: 40.67 | Val: 35.62
Epoch 9 | Train: 32.76 | Val: 30.64
Epoch 10 | Train: 27.02 | Val: 24.22
Epoch 11 | Train: 22.56 | Val: 21.30
Epoch 12 | Train: 19.35 | Val: 17.23
Epoch 13 | Train: 16.33 | Val: 15.42
Epoch 14 | Train: 13.83 | Val: 14.03
Epoch 15 | Train: 12.24 | Val: 12.01
Epoch 16 | Train: 10.69 | Val: 9.86
Epoch 17 | Train: 9.56 | Val: 9.13
Epoch 18 | Train: 8.61 | Val: 9.40
Epoch 19 | Train: 8.03 | Val: 8.69
Epoch 20 | Train: 7.36 | Val: 7.28
Epoch 21 | Train: 6.77 | Val: 6.33
Epoch 22 | Train: 6.40 | Val: 6.16
Epoch 23 | Train: 5.99 | Val: 5.66
Epoch 24 | Train: 5.77 | Val: 5.38
Epoch 25 | Train: 5.43 | Val: 5.83
Epoch 26 | Train: 5.28 | Val: 5.04
Epoch 27 | Train: 5.06 | Val: 5.08
Epoch 28 | Train: 4.84 | Val: 4.86
Epoch 29 | Train: 4.86 | Val: 6.05
Epoch 30 | Train: 4.51 | Val: 5.14
Epoch 31 | Train: 4.54 | Val: 4.53
Epoch 32 | Train: 4.26 | Val: 4.65
Epoch 33 | Train: 4.28 | Val: 4.55
Epoch 34 | Train: 4.08 | Val: 4.71
Epoch 35 | Train: 4.03 | Val: 5.60
Epoch 36 | Train: 4.01 | Val: 4.71
Early stopping en epoch 36

Entrenando modelo [256, 128, 64] con lr=0.001
Epoch 1 | Train: 594.14 | Val: 246.05
Epoch 2 | Train: 119.03 | Val: 48.72
Epoch 3 | Train: 23.34 | Val: 14.25
Epoch 4 | Train: 11.30 | Val: 9.03
Epoch 5 | Train: 7.92 | Val: 6.65
Epoch 6 | Train: 5.30 | Val: 5.62
Epoch 7 | Train: 4.09 | Val: 3.20
Epoch 8 | Train: 3.27 | Val: 3.44
Epoch 9 | Train: 3.14 | Val: 2.70
Epoch 10 | Train: 3.00 | Val: 2.58
Epoch 11 | Train: 2.48 | Val: 2.45
Epoch 12 | Train: 2.45 | Val: 2.54
Epoch 13 | Train: 2.32 | Val: 3.55
Epoch 14 | Train: 2.31 | Val: 2.77
Epoch 15 | Train: 2.15 | Val: 1.86
Epoch 16 | Train: 2.03 | Val: 2.83
Epoch 17 | Train: 2.08 | Val: 2.41
Epoch 18 | Train: 2.08 | Val: 4.12
Epoch 19 | Train: 2.04 | Val: 2.27
Epoch 20 | Train: 1.87 | Val: 3.32
Early stopping en epoch 20

Entrenando modelo [256, 128, 64] con lr=0.0005
Epoch 1 | Train: 701.73 | Val: 444.11
Epoch 2 | Train: 288.60 | Val: 177.29
Epoch 3 | Train: 116.22 | Val: 71.71
Epoch 4 | Train: 54.47 | Val: 42.50
Epoch 5 | Train: 36.25 | Val: 29.26
Epoch 6 | Train: 26.82 | Val: 22.21
Epoch 7 | Train: 21.20 | Val: 18.08
Epoch 8 | Train: 17.66 | Val: 15.70
Epoch 9 | Train: 14.96 | Val: 13.68
Epoch 10 | Train: 12.41 | Val: 11.18
Epoch 11 | Train: 10.28 | Val: 9.41
Epoch 12 | Train: 8.43 | Val: 7.40
Epoch 13 | Train: 6.50 | Val: 6.18
Epoch 14 | Train: 5.71 | Val: 11.68
Epoch 15 | Train: 4.77 | Val: 4.33
Epoch 16 | Train: 3.96 | Val: 3.61
Epoch 17 | Train: 3.44 | Val: 4.05
Epoch 18 | Train: 3.01 | Val: 3.13
Epoch 19 | Train: 3.06 | Val: 2.60
Epoch 20 | Train: 2.76 | Val: 2.36
Epoch 21 | Train: 2.49 | Val: 2.62
Epoch 22 | Train: 2.55 | Val: 2.62
Epoch 23 | Train: 2.59 | Val: 2.44
Epoch 24 | Train: 2.11 | Val: 2.13
Epoch 25 | Train: 2.45 | Val: 2.46
Epoch 26 | Train: 2.29 | Val: 1.93
Epoch 27 | Train: 2.28 | Val: 1.81
Epoch 28 | Train: 1.95 | Val: 2.12
Epoch 29 | Train: 2.24 | Val: 1.89
Epoch 30 | Train: 2.09 | Val: 1.98
Epoch 31 | Train: 2.02 | Val: 2.20
Epoch 32 | Train: 2.02 | Val: 2.52
Early stopping en epoch 32

In [124]:
for arch in arquitecturas:
    for lr in learning_rates:
        for dropout in dropouts:  
            
            model = PVModelV2(arch, dropout=dropout)
            
            print(f"\nEntrenando modelo {arch} | lr={lr} | dropout={dropout}")
            
            train_model(arch, lr, epochs, model)

Entrenando modelo [64, 32, 16] | lr=0.001 | dropout=0.1
Epoch 1 | Train: 2044.93 | Val: 1289.77
Epoch 2 | Train: 546.41 | Val: 111.36
Epoch 3 | Train: 145.20 | Val: 53.61
Epoch 4 | Train: 120.15 | Val: 40.98
Epoch 5 | Train: 106.37 | Val: 50.62
Epoch 6 | Train: 98.34 | Val: 27.53
Epoch 7 | Train: 93.51 | Val: 20.17
Epoch 8 | Train: 85.71 | Val: 24.15
Epoch 9 | Train: 82.17 | Val: 19.88
Epoch 10 | Train: 79.16 | Val: 19.27
Epoch 11 | Train: 74.24 | Val: 19.24
Epoch 12 | Train: 73.49 | Val: 20.91
Epoch 13 | Train: 70.00 | Val: 29.13
Epoch 14 | Train: 67.84 | Val: 19.68
Epoch 15 | Train: 66.18 | Val: 20.77
Epoch 16 | Train: 63.68 | Val: 19.87
Early stopping en epoch 16

Entrenando modelo [64, 32, 16] | lr=0.001 | dropout=0.2
Epoch 1 | Train: 1893.08 | Val: 1039.87
Epoch 2 | Train: 438.16 | Val: 145.83
Epoch 3 | Train: 183.81 | Val: 77.51
Epoch 4 | Train: 167.10 | Val: 59.93
Epoch 5 | Train: 156.16 | Val: 56.66
Epoch 6 | Train: 148.31 | Val: 43.32
Epoch 7 | Train: 141.11 | Val: 50.83
Epoch 8 | Train: 140.44 | Val: 39.97
Epoch 9 | Train: 135.74 | Val: 39.94
Epoch 10 | Train: 134.88 | Val: 35.41
Epoch 11 | Train: 132.53 | Val: 35.72
Epoch 12 | Train: 128.63 | Val: 30.00
Epoch 13 | Train: 128.49 | Val: 32.35
Epoch 14 | Train: 127.12 | Val: 29.14
Epoch 15 | Train: 125.20 | Val: 30.48
Epoch 16 | Train: 123.43 | Val: 30.65
Epoch 17 | Train: 123.03 | Val: 33.39
Epoch 18 | Train: 120.32 | Val: 27.28
Epoch 19 | Train: 121.53 | Val: 28.75
Epoch 20 | Train: 119.49 | Val: 32.00
Epoch 21 | Train: 118.39 | Val: 39.38
Epoch 22 | Train: 116.88 | Val: 29.96
Epoch 23 | Train: 113.36 | Val: 22.48
Epoch 24 | Train: 112.93 | Val: 24.00
Epoch 25 | Train: 114.00 | Val: 25.10
Epoch 26 | Train: 112.02 | Val: 24.97
Epoch 27 | Train: 111.97 | Val: 23.12
Epoch 28 | Train: 109.34 | Val: 23.27
Early stopping en epoch 28

Entrenando modelo [64, 32, 16] | lr=0.0005 | dropout=0.1
Epoch 1 | Train: 2252.16 | Val: 2013.83
Epoch 2 | Train: 1522.48 | Val: 1022.30
Epoch 3 | Train: 647.03 | Val: 350.95
Epoch 4 | Train: 228.33 | Val: 97.38
Epoch 5 | Train: 130.37 | Val: 43.03
Epoch 6 | Train: 110.25 | Val: 33.49
Epoch 7 | Train: 103.46 | Val: 25.05
Epoch 8 | Train: 97.90 | Val: 25.24
Epoch 9 | Train: 97.27 | Val: 21.55
Epoch 10 | Train: 91.64 | Val: 20.65
Epoch 11 | Train: 90.08 | Val: 16.34
Epoch 12 | Train: 87.71 | Val: 17.78
Epoch 13 | Train: 83.98 | Val: 15.30
Epoch 14 | Train: 80.63 | Val: 15.35
Epoch 15 | Train: 77.99 | Val: 11.30
Epoch 16 | Train: 77.67 | Val: 15.90
Epoch 17 | Train: 75.29 | Val: 12.92
Epoch 18 | Train: 73.12 | Val: 9.33
Epoch 19 | Train: 71.77 | Val: 12.79
Epoch 20 | Train: 70.55 | Val: 11.22
Epoch 21 | Train: 69.67 | Val: 12.67
Epoch 22 | Train: 69.71 | Val: 10.80
Epoch 23 | Train: 69.10 | Val: 11.94
Early stopping en epoch 23

Entrenando modelo [64, 32, 16] | lr=0.0005 | dropout=0.2
Epoch 1 | Train: 2241.31 | Val: 1981.24
Epoch 2 | Train: 1464.68 | Val: 985.72
Epoch 3 | Train: 614.98 | Val: 329.96
Epoch 4 | Train: 258.69 | Val: 111.26
Epoch 5 | Train: 181.87 | Val: 64.76
Epoch 6 | Train: 160.92 | Val: 67.97
Epoch 7 | Train: 152.87 | Val: 63.97
Epoch 8 | Train: 149.33 | Val: 68.24
Epoch 9 | Train: 145.58 | Val: 77.17
Epoch 10 | Train: 147.04 | Val: 65.53
Epoch 11 | Train: 142.84 | Val: 63.53
Epoch 12 | Train: 140.35 | Val: 55.17
Epoch 13 | Train: 137.36 | Val: 54.59
Epoch 14 | Train: 134.92 | Val: 56.90
Epoch 15 | Train: 133.45 | Val: 47.58
Epoch 16 | Train: 130.25 | Val: 50.02
Epoch 17 | Train: 127.26 | Val: 45.00
Epoch 18 | Train: 125.78 | Val: 51.53
Epoch 19 | Train: 126.08 | Val: 47.29
Epoch 20 | Train: 124.64 | Val: 49.56
Epoch 21 | Train: 121.86 | Val: 46.37
Epoch 22 | Train: 121.56 | Val: 42.57
Epoch 23 | Train: 120.84 | Val: 47.74
Epoch 24 | Train: 122.90 | Val: 43.09
Epoch 25 | Train: 120.36 | Val: 42.33
Epoch 26 | Train: 118.90 | Val: 42.15
Epoch 27 | Train: 119.91 | Val: 47.24
Epoch 28 | Train: 118.42 | Val: 42.10
Epoch 29 | Train: 117.58 | Val: 47.55
Epoch 30 | Train: 116.26 | Val: 45.87
Epoch 31 | Train: 116.46 | Val: 44.85
Epoch 32 | Train: 115.71 | Val: 40.08
Epoch 33 | Train: 115.04 | Val: 41.71
Epoch 34 | Train: 115.15 | Val: 44.20
Epoch 35 | Train: 115.41 | Val: 42.66
Epoch 36 | Train: 115.09 | Val: 43.80
Epoch 37 | Train: 113.07 | Val: 40.41
Early stopping en epoch 37

Entrenando modelo [128, 64, 32] | lr=0.001 | dropout=0.1
Epoch 1 | Train: 1388.27 | Val: 291.46
Epoch 2 | Train: 177.68 | Val: 61.27
Epoch 3 | Train: 111.05 | Val: 38.72
Epoch 4 | Train: 92.54 | Val: 25.66
Epoch 5 | Train: 78.43 | Val: 22.16
Epoch 6 | Train: 70.17 | Val: 18.66
Epoch 7 | Train: 63.68 | Val: 15.15
Epoch 8 | Train: 56.46 | Val: 8.84
Epoch 9 | Train: 53.05 | Val: 11.59
Epoch 10 | Train: 49.45 | Val: 7.36
Epoch 11 | Train: 48.87 | Val: 12.01
Epoch 12 | Train: 46.90 | Val: 9.03
Epoch 13 | Train: 47.14 | Val: 7.32
Epoch 14 | Train: 44.16 | Val: 9.26
Epoch 15 | Train: 41.07 | Val: 9.81
Epoch 16 | Train: 39.57 | Val: 7.48
Epoch 17 | Train: 40.88 | Val: 6.33
Epoch 18 | Train: 39.52 | Val: 6.37
Epoch 19 | Train: 38.99 | Val: 8.31
Epoch 20 | Train: 37.49 | Val: 4.28
Epoch 21 | Train: 38.11 | Val: 4.12
Epoch 22 | Train: 36.49 | Val: 4.82
Epoch 23 | Train: 37.70 | Val: 4.47
Epoch 24 | Train: 35.27 | Val: 5.18
Epoch 25 | Train: 35.86 | Val: 4.88
Epoch 26 | Train: 34.52 | Val: 5.31
Early stopping en epoch 26

Entrenando modelo [128, 64, 32] | lr=0.001 | dropout=0.2
Epoch 1 | Train: 1388.80 | Val: 348.62
Epoch 2 | Train: 205.65 | Val: 64.23
Epoch 3 | Train: 135.25 | Val: 43.66
Epoch 4 | Train: 115.57 | Val: 38.15
Epoch 5 | Train: 102.93 | Val: 31.02
Epoch 6 | Train: 96.79 | Val: 20.87
Epoch 7 | Train: 91.39 | Val: 17.90
Epoch 8 | Train: 86.56 | Val: 16.93
Epoch 9 | Train: 83.10 | Val: 12.38
Epoch 10 | Train: 77.61 | Val: 12.61
Epoch 11 | Train: 77.69 | Val: 11.03
Epoch 12 | Train: 75.10 | Val: 11.73
Epoch 13 | Train: 71.75 | Val: 13.36
Epoch 14 | Train: 72.98 | Val: 9.78
Epoch 15 | Train: 69.88 | Val: 9.69
Epoch 16 | Train: 69.92 | Val: 9.74
Epoch 17 | Train: 70.31 | Val: 10.88
Epoch 18 | Train: 68.56 | Val: 7.96
Epoch 19 | Train: 66.46 | Val: 5.52
Epoch 20 | Train: 66.07 | Val: 10.73
Epoch 21 | Train: 65.82 | Val: 9.22
Epoch 22 | Train: 64.09 | Val: 10.04
Epoch 23 | Train: 63.52 | Val: 5.46
Epoch 24 | Train: 62.55 | Val: 5.17
Epoch 25 | Train: 63.72 | Val: 6.32
Epoch 26 | Train: 61.50 | Val: 5.92
Epoch 27 | Train: 61.15 | Val: 6.03
Epoch 28 | Train: 61.30 | Val: 7.73
Epoch 29 | Train: 61.92 | Val: 12.89
Early stopping en epoch 29

Entrenando modelo [128, 64, 32] | lr=0.0005 | dropout=0.1
Epoch 1 | Train: 2077.64 | Val: 1467.23
Epoch 2 | Train: 823.57 | Val: 331.52
Epoch 3 | Train: 215.66 | Val: 79.54
Epoch 4 | Train: 128.42 | Val: 53.01
Epoch 5 | Train: 110.26 | Val: 50.14
Epoch 6 | Train: 99.25 | Val: 34.00
Epoch 7 | Train: 92.00 | Val: 29.74
Epoch 8 | Train: 84.50 | Val: 27.22
Epoch 9 | Train: 77.53 | Val: 22.04
Epoch 10 | Train: 71.22 | Val: 18.37
Epoch 11 | Train: 68.19 | Val: 18.49
Epoch 12 | Train: 64.82 | Val: 13.11
Epoch 13 | Train: 60.47 | Val: 14.51
Epoch 14 | Train: 59.95 | Val: 12.98
Epoch 15 | Train: 58.70 | Val: 11.52
Epoch 16 | Train: 54.84 | Val: 12.48
Epoch 17 | Train: 51.78 | Val: 11.05
Epoch 18 | Train: 51.31 | Val: 9.57
Epoch 19 | Train: 49.85 | Val: 9.91
Epoch 20 | Train: 49.17 | Val: 9.59
Epoch 21 | Train: 48.20 | Val: 8.92
Epoch 22 | Train: 48.64 | Val: 9.24
Epoch 23 | Train: 47.14 | Val: 9.71
Epoch 24 | Train: 46.91 | Val: 8.92
Epoch 25 | Train: 45.42 | Val: 8.21
Epoch 26 | Train: 45.16 | Val: 8.71
Epoch 27 | Train: 45.60 | Val: 7.75
Epoch 28 | Train: 44.28 | Val: 7.48
Epoch 29 | Train: 44.16 | Val: 7.85
Epoch 30 | Train: 42.82 | Val: 8.23
Epoch 31 | Train: 42.35 | Val: 7.86
Epoch 32 | Train: 43.63 | Val: 7.82
Epoch 33 | Train: 43.16 | Val: 6.96
Epoch 34 | Train: 41.41 | Val: 10.04
Epoch 35 | Train: 40.84 | Val: 9.80
Epoch 36 | Train: 42.18 | Val: 12.31
Epoch 37 | Train: 41.43 | Val: 7.24
Epoch 38 | Train: 39.98 | Val: 7.93
Early stopping en epoch 38

Entrenando modelo [128, 64, 32] | lr=0.0005 | dropout=0.2
Epoch 1 | Train: 1974.38 | Val: 1346.30
Epoch 2 | Train: 774.89 | Val: 291.20
Epoch 3 | Train: 254.36 | Val: 97.68
Epoch 4 | Train: 161.39 | Val: 56.81
Epoch 5 | Train: 138.46 | Val: 46.68
Epoch 6 | Train: 127.62 | Val: 46.35
Epoch 7 | Train: 118.72 | Val: 37.36
Epoch 8 | Train: 113.38 | Val: 38.16
Epoch 9 | Train: 108.20 | Val: 31.07
Epoch 10 | Train: 102.88 | Val: 28.53
Epoch 11 | Train: 95.42 | Val: 20.95
Epoch 12 | Train: 92.14 | Val: 20.98
Epoch 13 | Train: 89.23 | Val: 14.83
Epoch 14 | Train: 84.67 | Val: 17.04
Epoch 15 | Train: 83.62 | Val: 14.10
Epoch 16 | Train: 81.31 | Val: 15.75
Epoch 17 | Train: 76.23 | Val: 13.26
Epoch 18 | Train: 75.96 | Val: 14.74
Epoch 19 | Train: 72.08 | Val: 10.32
Epoch 20 | Train: 72.16 | Val: 10.97
Epoch 21 | Train: 70.96 | Val: 13.05
Epoch 22 | Train: 69.83 | Val: 9.69
Epoch 23 | Train: 67.44 | Val: 11.20
Epoch 24 | Train: 68.25 | Val: 8.72
Epoch 25 | Train: 66.82 | Val: 8.04
Epoch 26 | Train: 65.58 | Val: 10.67
Epoch 27 | Train: 66.59 | Val: 8.15
Epoch 28 | Train: 64.09 | Val: 8.62
Epoch 29 | Train: 62.89 | Val: 15.97
Epoch 30 | Train: 63.51 | Val: 8.24
Early stopping en epoch 30

Entrenando modelo [256, 128, 64] | lr=0.001 | dropout=0.1
Epoch 1 | Train: 989.78 | Val: 98.28
Epoch 2 | Train: 125.67 | Val: 54.68
Epoch 3 | Train: 96.69 | Val: 33.32
Epoch 4 | Train: 78.45 | Val: 23.51
Epoch 5 | Train: 66.61 | Val: 20.31
Epoch 6 | Train: 58.55 | Val: 10.59
Epoch 7 | Train: 52.79 | Val: 9.29
Epoch 8 | Train: 46.93 | Val: 9.99
Epoch 9 | Train: 43.47 | Val: 7.32
Epoch 10 | Train: 37.95 | Val: 7.50
Epoch 11 | Train: 35.91 | Val: 5.66
Epoch 12 | Train: 34.98 | Val: 4.90
Epoch 13 | Train: 33.92 | Val: 4.63
Epoch 14 | Train: 31.02 | Val: 5.68
Epoch 15 | Train: 28.58 | Val: 3.49
Epoch 16 | Train: 29.26 | Val: 5.93
Epoch 17 | Train: 27.25 | Val: 4.83
Epoch 18 | Train: 26.04 | Val: 4.76
Epoch 19 | Train: 25.66 | Val: 4.38
Epoch 20 | Train: 25.22 | Val: 4.05
Early stopping en epoch 20

Entrenando modelo [256, 128, 64] | lr=0.001 | dropout=0.2
Epoch 1 | Train: 976.21 | Val: 116.56
Epoch 2 | Train: 155.45 | Val: 63.36
Epoch 3 | Train: 118.75 | Val: 47.96
Epoch 4 | Train: 95.28 | Val: 27.96
Epoch 5 | Train: 80.46 | Val: 18.46
Epoch 6 | Train: 71.95 | Val: 12.38
Epoch 7 | Train: 63.78 | Val: 13.74
Epoch 8 | Train: 58.35 | Val: 11.93
Epoch 9 | Train: 54.15 | Val: 12.17
Epoch 10 | Train: 52.01 | Val: 9.38
Epoch 11 | Train: 49.76 | Val: 12.48
Epoch 12 | Train: 49.02 | Val: 6.98
Epoch 13 | Train: 45.58 | Val: 6.44
Epoch 14 | Train: 45.48 | Val: 5.46
Epoch 15 | Train: 44.44 | Val: 6.45
Epoch 16 | Train: 43.97 | Val: 5.77
Epoch 17 | Train: 43.53 | Val: 7.18
Epoch 18 | Train: 39.81 | Val: 8.09
Epoch 19 | Train: 40.84 | Val: 4.74
Epoch 20 | Train: 40.70 | Val: 4.39
Epoch 21 | Train: 38.65 | Val: 4.79
Epoch 22 | Train: 40.06 | Val: 5.51
Epoch 23 | Train: 36.73 | Val: 5.34
Epoch 24 | Train: 38.36 | Val: 4.18
Epoch 25 | Train: 37.01 | Val: 6.60
Epoch 26 | Train: 36.42 | Val: 4.48
Epoch 27 | Train: 36.91 | Val: 5.65
Epoch 28 | Train: 35.59 | Val: 3.80
Epoch 29 | Train: 35.44 | Val: 4.69
Epoch 30 | Train: 37.82 | Val: 4.80
Epoch 31 | Train: 34.17 | Val: 4.62
Epoch 32 | Train: 35.02 | Val: 5.26
Epoch 33 | Train: 34.32 | Val: 4.69
Early stopping en epoch 33

Entrenando modelo [256, 128, 64] | lr=0.0005 | dropout=0.1
Epoch 1 | Train: 1670.07 | Val: 686.40
Epoch 2 | Train: 317.90 | Val: 99.79
Epoch 3 | Train: 138.85 | Val: 62.41
Epoch 4 | Train: 113.82 | Val: 49.63
Epoch 5 | Train: 98.17 | Val: 40.05
Epoch 6 | Train: 88.78 | Val: 33.90
Epoch 7 | Train: 78.35 | Val: 24.33
Epoch 8 | Train: 71.08 | Val: 20.68
Epoch 9 | Train: 64.70 | Val: 23.03
Epoch 10 | Train: 59.01 | Val: 13.28
Epoch 11 | Train: 55.90 | Val: 12.08
Epoch 12 | Train: 53.12 | Val: 15.18
Epoch 13 | Train: 48.75 | Val: 12.08
Epoch 14 | Train: 46.02 | Val: 10.92
Epoch 15 | Train: 42.92 | Val: 7.80
Epoch 16 | Train: 40.21 | Val: 7.75
Epoch 17 | Train: 39.83 | Val: 8.76
Epoch 18 | Train: 35.77 | Val: 7.62
Epoch 19 | Train: 35.74 | Val: 8.24
Epoch 20 | Train: 34.69 | Val: 5.75
Epoch 21 | Train: 33.50 | Val: 6.58
Epoch 22 | Train: 33.51 | Val: 8.16
Epoch 23 | Train: 32.15 | Val: 4.80
Epoch 24 | Train: 30.64 | Val: 6.57
Epoch 25 | Train: 29.19 | Val: 5.78
Epoch 26 | Train: 29.16 | Val: 5.11
Epoch 27 | Train: 27.33 | Val: 4.65
Epoch 28 | Train: 29.16 | Val: 4.22
Epoch 29 | Train: 27.30 | Val: 7.47
Epoch 30 | Train: 27.33 | Val: 3.64
Epoch 31 | Train: 26.13 | Val: 4.13
Epoch 32 | Train: 27.66 | Val: 4.70
Epoch 33 | Train: 25.68 | Val: 5.48
Epoch 34 | Train: 25.07 | Val: 5.10
Epoch 35 | Train: 24.69 | Val: 3.59
Epoch 36 | Train: 24.98 | Val: 4.21
Epoch 37 | Train: 24.18 | Val: 4.31
Epoch 38 | Train: 25.04 | Val: 4.82
Epoch 39 | Train: 24.50 | Val: 3.37
Epoch 40 | Train: 23.69 | Val: 3.97
Epoch 41 | Train: 24.03 | Val: 4.72
Epoch 42 | Train: 23.46 | Val: 5.61
Epoch 43 | Train: 22.19 | Val: 2.80
Epoch 44 | Train: 22.63 | Val: 4.90
Epoch 45 | Train: 22.10 | Val: 3.60
Epoch 46 | Train: 21.62 | Val: 4.52
Epoch 47 | Train: 22.07 | Val: 3.53
Epoch 48 | Train: 22.21 | Val: 3.61
Early stopping en epoch 48

Entrenando modelo [256, 128, 64] | lr=0.0005 | dropout=0.2
Epoch 1 | Train: 1624.72 | Val: 716.72
Epoch 2 | Train: 339.33 | Val: 109.80
Epoch 3 | Train: 157.79 | Val: 68.22
Epoch 4 | Train: 129.96 | Val: 52.59
Epoch 5 | Train: 113.06 | Val: 40.29
Epoch 6 | Train: 101.87 | Val: 31.18
Epoch 7 | Train: 92.30 | Val: 23.20
Epoch 8 | Train: 82.47 | Val: 18.68
Epoch 9 | Train: 72.87 | Val: 17.72
Epoch 10 | Train: 68.19 | Val: 12.94
Epoch 11 | Train: 64.68 | Val: 12.25
Epoch 12 | Train: 59.64 | Val: 9.52
Epoch 13 | Train: 55.74 | Val: 12.46
Epoch 14 | Train: 53.98 | Val: 12.13
Epoch 15 | Train: 53.11 | Val: 7.41
Epoch 16 | Train: 48.39 | Val: 8.71
Epoch 17 | Train: 47.45 | Val: 8.39
Epoch 18 | Train: 47.29 | Val: 5.61
Epoch 19 | Train: 44.19 | Val: 6.42
Epoch 20 | Train: 44.03 | Val: 5.84
Epoch 21 | Train: 44.16 | Val: 6.57
Epoch 22 | Train: 44.60 | Val: 5.70
Epoch 23 | Train: 43.43 | Val: 7.45
Early stopping en epoch 23

# ENTRENAMIENTOS FINALES DE LOS MEJORES MODELOS